### ISSUE TITLE
Large number of images stack on each other

### ISSUE THREAD

**Issue by sometechguy** [biigpongsatorn/vue-infinite-slide-bar#1]
It seems like you have a max length set for the bar.  If I have more than 10-15 images they start stacking up on each other thus ruining the experience.  How do I get around it?

**Comment by biigpongsatorn** [comment]
Yes, Now this component will limit max width <= 100 vw, Can you fix it for unlimit length set of the bar ?

**Comment by sometechguy** [comment]
Which file do I need to edit?  may be you can update it yourself.

**Comment by xyNNN** [comment]
Anyone have an idea how to fix this?

**Comment by frncsdrk** [comment]
@biigpongsatorn @xyNNN An implementation for an unlimited amount of images might be too messy, as calculating of the summed width of all images would be necessary. I would instead suggest to provide the user of the component with the possibility to change the width of the bar (already possible via `barStyle`) and container themselves. That way they are free to tweak the width according to the number of images or implement the more intelligent solution if they need to.

**Comment by kissa1001** [comment]
I found out that if you remove float: left and width: 50% from vifnslb-bar and then apply display: flex to vifnslb-container then the stacking issue disappears.

**Comment by biigpongsatorn** [comment]
@kissa1001 Thank you for your idea.

@sometechguy  @xyNNN  
Now I just publish version `1.0.9` to fix this issue.

**Comment by xyNNN** [comment]
Thanks @biigpongsatorn !
