### ISSUE TITLE
How to pause the slide  when mouse is placed on the slider?

### ISSUE THREAD

**Issue by sushiljic** [biigpongsatorn/vue-infinite-slide-bar#6]
How do i achieve a feature of marquee pausing the movement whenever mouse is being placed on it?

**Comment by biigpongsatorn** [comment]
Currently, you can't.
But you can use the event `mouseover` and `mouseleave` to set the duration of slider.

example

```html
    <infinite-slide-bar
      :barStyle="{ background: '#42b883', padding: '5px 0' }"
      :duration="speed"
      @mouseover.native="speed = '99s'"
      @mouseleave.native="speed = '12s'"
    >
      <span style="color: #fff;">Helo World, I love Vue Infinite Slide Bar</span>
    </infinite-slide-bar>
```

**Comment by dennisfrijlink** [comment]
`.vifnslb-element:hover{
    -webkit-animation-play-state:paused;
    -moz-animation-play-state:paused;
    -o-animation-play-state:paused;
    animation-play-state:paused;
  }`
