### ISSUE TITLE
CDN link / ES 2015

### ISSUE THREAD

**Issue by solamichealolawale** [biigpongsatorn/vue-infinite-slide-bar#7]
I don't want to use npm in my simple project, can I get a link to download the js from or a CDN version.
Thanks in advance

**Comment by biigpongsatorn** [comment]
@solamichealolawale Please clone  this repo and run `npm run build:lib` by yourself and copy bundle file to your project.

**Comment by solamichealolawale** [comment]
> VM1081:1 Uncaught ReferenceError: InfiniteSlideBar is not defined
>     at <anonymous>:1:1


After copying the bundled file to my project, I use 
`Vue.component('infinite-slide-bar', InfiniteSlideBar);`
and after that in my view I use
`<infinite-slide-bar :barStyle="{ background: '#42b883', padding: '5px 0' }">
                            <span style="color: #fff;">Helo World, I love Vue Infinite Slide Bar</span>
                        </infinite-slide-bar>`
